# -*- coding: utf-8 -*-
"""bahan 01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PC6_ACYhanT0OJRZxq0h9_0kEaCVLz9z
"""

from google.colab import drive
drive.mount('/content/drive')

!unzip -o -q "/content/drive/MyDrive/dataset_wajah.zip" -d "/content/dataset_siap"

print("--- PROSES SELESAI ---")
print("Data kamu sekarang sudah rapi di server Google Colab.")

# Kita ekstrak file zip yang ada di dalam folder tersebut
!unzip -o -q "/content/dataset_siap/dataset_wajah.zip" -d "/content/dataset_akhir"

# Kita cek lagi isinya sekarang
import os
print("Isi folder dataset_akhir:", os.listdir('/content/dataset_akhir'))

import os

# Kita cek isi di dalam folder ddata
path_cek = '/content/dataset_akhir/ddata'
print("Isi di dalam folder ddata adalah:", os.listdir(path_cek))

import os

# Menentukan alamat folder utama
train_dir = '/content/dataset_akhir/ddata/train'
test_dir = '/content/dataset_akhir/ddata/test'

# Fungsi untuk menghitung jumlah file di dalam folder
def hitung_data(directory):
    for folder_kelas in os.listdir(directory):
        path = os.path.join(directory, folder_kelas)
        # Hanya hitung jika itu adalah folder
        if os.path.isdir(path):
            jumlah = len(os.listdir(path))
            print(f"Folder: {folder_kelas} | Jumlah Foto: {jumlah}")

print("--- DATA TRAINING ---")
hitung_data(train_dir)

print("\n--- DATA TESTING ---")
hitung_data(test_dir)

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Konfigurasi ukuran gambar dan batch
# Batch size 32 artinya AI belajar 32 foto sekaligus dalam satu tarikan napas
IMG_SIZE = (128, 128)
BATCH_SIZE = 32

# 1. Menyiapkan generator (tukang masak data)
datagen = ImageDataGenerator(rescale=1./255)

# 2. Mengambil data dari folder train
print("Mengambil data training...")
train_generator = datagen.flow_from_directory(
    train_dir,
    target_size = IMG_SIZE,
    batch_size = BATCH_SIZE,
    class_mode = 'binary' # Karena cuma ada 2 kelas: Real & Fake
)

# 3. Mengambil data dari folder test
print("\nMengambil data testing...")
test_generator = datagen.flow_from_directory(
    test_dir,
    target_size = IMG_SIZE,
    batch_size = BATCH_SIZE,
    class_mode = 'binary'
)

from tensorflow.keras import layers, models

# Membangun Model CNN
model = models.Sequential([
    # Layer 1: Mencari pola dasar (garis/tepi)
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)),
    layers.MaxPooling2D(2, 2),

    # Layer 2: Mencari pola bentuk wajah
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),

    # Layer 3: Pola yang lebih kompleks
    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),

    # Mengubah data jadi satu baris panjang
    layers.Flatten(),

    # Otak utama (Dense Layer)
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5), # Biar AI nggak "hafal mati" (overfitting)

    # Output: 1 neuron (karena cuma Real atau Fake)
    layers.Dense(1, activation='sigmoid')
])

# Compile Model (Menentukan cara AI belajar)
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Menampilkan ringkasan model
model.summary()

# Proses Training (Belajar)
history = model.fit(
    train_generator,
    epochs=10, # Kita coba 10 putaran dulu
    validation_data=test_generator
)

# Simpan modelnya kalau sudah selesai biar gak hilang
model.save('model_deteksi_wajah_v1.h5')
print("--- TRAINING SELESAI DAN MODEL DISIMPAN ---")

import matplotlib.pyplot as plt

# Mengambil data dari history training
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']
epochs_range = range(1, len(acc) + 1)

# Membuat grafik Akurasi
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.title('Grafik Akurasi')
plt.legend()

# Membuat grafik Loss
plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.title('Grafik Loss')
plt.legend()

plt.show()

import numpy as np
from google.colab import files
from tensorflow.keras.preprocessing import image

# Fungsi untuk memprediksi gambar yang diupload
def prediksi_gambar():
    uploaded = files.upload()

    for fn in uploaded.keys():
        # Memuat gambar dan meresize sesuai ukuran training (128x128)
        path = fn
        img = image.load_img(path, target_size=(128, 128))

        # Menampilkan gambar yang diupload
        plt.imshow(img)
        plt.axis('off')
        plt.show()

        # Mengubah gambar menjadi array yang bisa dibaca AI
        x = image.img_to_array(img)
        x = np.expand_dims(x, axis=0)
        x = x / 255.0 # Normalisasi sama seperti saat training

        # Proses Prediksi
        classes = model.predict(x)

        # Interpretasi hasil (karena binary, biasanya 0=Fake dan 1=Real atau sebaliknya)
        # Kita cek urutan kelasnya dulu
        if classes[0] > 0.5:
            print(f"Hasil Prediksi: REAL (Skor: {classes[0][0]:.4f})")
        else:
            print(f"Hasil Prediksi: FAKE (Skor: {classes[0][0]:.4f})")

# Jalankan fungsinya
prediksi_gambar()